name: seaweed-growth-model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas=1.4.3
  - setuptools=61.2.0
  - pytest=7.1.2
  - numpy=1.23.1
  - matplotlib=3.5.1
  - geopandas=0.11.1
  - xarray = 0.20.1
