site_name: Seaweed Growth Model


# Repository
repo_name: Seaweed Growth Model
repo_url: https://github.com/allfed/Seaweed-Growth-Model
edit_uri: ""
# Copyright
copyright: ALLFED

docs_dir: "docs/sources"

plugins:
  - search

theme:
  name: 'readthedocs'
  custom_dir: 'docs'
  palette:
    primary: 'white'
  logo: 'assets/images/logo_full.svg'
  favicon: 'assets/images/favicon.svg'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - instant
nav:
  - Home: index.md
  - modules:
    - src:
      - model:
        - ocean_section: modules/src/model/ocean_section.md
        - seaweed_growth: modules/src/model/seaweed_growth.md
        - seaweed_model: modules/src/model/seaweed_model.md
      - plotting:
        - plotter_lme: modules/src/plotting/plotter_lme.md
      - processing:
        - preprocessing: modules/src/processing/preprocessing.md
        - read_files: modules/src/processing/read_files.md
